name: Deploy OS specific binaries

on:
  push:
    branches: [binaries]

jobs:
  linux:
    runs-on: ubuntu-latest
    container: centos6

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install .
          python -m pip install pyinstaller

      - name: Build binary
        run: |
          cd src
          python -m PyInstaller --clean -F --name black.elf --add-data blib2to3/:blib2to3 black/__main__.py

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: black.elf
          path: dist/black.elf
