name: Upload self-contained binaries

on:
  release:
    types: [published]

jobs:
  linux:
    runs-on: ubuntu-16.04

    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install .
          python -m pip install pyinstaller

      - name: Build binary
        run: |
          python -m PyInstaller --clean -F --name black.elf --add-data src/blib2to3:blib2to3 src/black/__main__.py

      - name: Upload binary as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist/black.elf
          asset_name: black.elf
          asset_content_type: application/x-executable

  windows:
    runs-on: windows-2019

    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install .
          python -m pip install pyinstaller

      - name: Build binary
        run: |
          python -m PyInstaller --clean -F --name black.exe --add-data 'src\blib2to3;blib2to3' src\black\__main__.py

      - name: Upload binary as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: dist/black.exe
          asset_name: black.exe
          asset_content_type: application/vnd.microsoft.portable-executable
